; Configurable parameters:
; SERIALCOM_SPEED = speed of the serial port (baud), global [env] section
; DATA_PIN = pin/GPIO for the LED strip data channel, specific [board] section
; CLOCK_PIN = pin/GPIO for the LED strip clock channel, specific [board] section
; LED_POWER_PIN = pin/GPIO for external relay power control, it will turn off (low state) if no serial data is received after 5 seconds
; LED_POWER_INVERT = if defined: off state is a high signal for the power relay, on state is a low signal

; MULTI-SEGMENT SUPPORT
; You can define second segment to handle. Add following parameters (with -D prefix to the build_flags sections).
; SECOND_SEGMENT_START_INDEX = start index of the second segment
; SECOND_SEGMENT_CLOCK_PIN = pin/GPIO for the second segment LED strip data channel
; SECOND_SEGMENT_DATA_PIN = pin/GPIO for the second segment LED strip clock channel
; SECOND_SEGMENT_REVERSED = if defined, the segment is reversed, the first LED of the second segment becomes the last

[platformio]
default_envs = esp32s3_sk6812

[env]
framework = arduino
extra_scripts = pre:extra_script.py
build_flags = -DSERIALCOM_SPEED=2000000

;==========================================================
; ESP32 board
;==========================================================
[esp32]
platform = espressif32@6.0.0
lib_deps = https://github.com/awawa-dev/NeoPixelBus.git#HyperSerialESP32
test_ignore =

[env:SK6812_RGBW_COLD]
build_flags = -DNEOPIXEL_RGBW -DCOLD_WHITE -DDATA_PIN=2 ${env.build_flags}
custom_prog_version = esp32_SK6812_RGBW_COLD

board = esp32dev
platform = ${esp32.platform}
lib_deps = ${esp32.lib_deps}
test_ignore = ${esp32.test_ignore}

[env:SK6812_RGBW_NEUTRAL]
build_flags = -DNEOPIXEL_RGBW -DDATA_PIN=2 ${env.build_flags}
custom_prog_version = esp32_SK6812_RGBW_NEUTRAL

board = esp32dev
platform = ${esp32.platform}
lib_deps = ${esp32.lib_deps}
test_ignore = ${esp32.test_ignore}

[env:WS281x_RGB]
build_flags = -DNEOPIXEL_RGB -DDATA_PIN=2 ${env.build_flags}
custom_prog_version = esp32_WS281x_RGB

board = esp32dev
platform = ${esp32.platform}
lib_deps = ${esp32.lib_deps}
test_ignore = ${esp32.test_ignore}

[env:SPI_APA102_SK9822_HD107]
build_flags = -DSPILED_APA102 -DDATA_PIN=2 -DCLOCK_PIN=4 ${env.build_flags}
custom_prog_version = esp32_SPI_APA102_SK9822_HD107

board = esp32dev
platform = ${esp32.platform}
lib_deps = ${esp32.lib_deps}
test_ignore = ${esp32.test_ignore}

[env:SPI_WS2801]
build_flags = -DSPILED_WS2801 -DDATA_PIN=2 -DCLOCK_PIN=4 ${env.build_flags}
custom_prog_version = esp32_SPI_WS2801

board = esp32dev
platform = ${esp32.platform}
lib_deps = ${esp32.lib_deps}
test_ignore = ${esp32.test_ignore}

;==========================================================
; ESP32-S3 board
;==========================================================
[env:esp32s3_sk6812]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
monitor_speed = 115200
upload_speed = 921600
lib_deps = https://github.com/awawa-dev/NeoPixelBus.git#HyperSerialESP32
build_flags =
    -DNEOPIXEL_RGBW
    -DDATA_PIN=2
    -DSERIALCOM_SPEED=2000000
    -DNeoEsp32I2s1Sk6812Method=NeoEsp32Rmt0Sk6812Method

;==========================================================
; ESP32-S2 board
;==========================================================
[esp32_lolin_s2_mini]
platform = espressif32@6.0.0
lib_deps = https://github.com/awawa-dev/NeoPixelBus.git#HyperSerialESP32
test_ignore = *

[env:s2_mini_SK6812_RGBW_COLD]
build_flags = -DNEOPIXEL_RGBW -DCOLD_WHITE -DDATA_PIN=2 ${env.build_flags}
custom_prog_version = esp32_s2_mini_SK6812_RGBW_COLD

board = lolin_s2_mini
board_build.mcu = esp32s2
platform = ${esp32_lolin_s2_mini.platform}
lib_deps = ${esp32_lolin_s2_mini.lib_deps}
test_ignore = ${esp32_lolin_s2_mini.test_ignore}

[env:s2_mini_SK6812_RGBW_NEUTRAL]
build_flags = -DNEOPIXEL_RGBW -DDATA_PIN=2 ${env.build_flags}
custom_prog_version = esp32_s2_mini_SK6812_RGBW_NEUTRAL

board = lolin_s2_mini
board_build.mcu = esp32s2
platform = ${esp32_lolin_s2_mini.platform}
lib_deps = ${esp32_lolin_s2_mini.lib_deps}
test_ignore = ${esp32_lolin_s2_mini.test_ignore}

[env:s2_mini_WS281x_RGB]
build_flags = -DNEOPIXEL_RGB -DDATA_PIN=2 ${env.build_flags}
custom_prog_version = esp32_s2_mini_WS281x_RGB

board = lolin_s2_mini
board_build.mcu = esp32s2
platform = ${esp32_lolin_s2_mini.platform}
lib_deps = ${esp32_lolin_s2_mini.lib_deps}
test_ignore = ${esp32_lolin_s2_mini.test_ignore}

[env:s2_mini_SPI_APA102_SK9822_HD107]
build_flags = -DSPILED_APA102 -DDATA_PIN=2 -DCLOCK_PIN=4 ${env.build_flags}
custom_prog_version = esp32_s2_mini_SPI_APA102_SK9822_HD107

board = lolin_s2_mini
board_build.mcu = esp32s2
platform = ${esp32_lolin_s2_mini.platform}
lib_deps = ${esp32_lolin_s2_mini.lib_deps}
test_ignore = ${esp32_lolin_s2_mini.test_ignore}

[env:s2_mini_SPI_WS2801]
build_flags = -DSPILED_WS2801 -DDATA_PIN=2 -DCLOCK_PIN=4 ${env.build_flags}
custom_prog_version = esp32_s2_mini_SPI_WS2801

board = lolin_s2_mini
board_build.mcu = esp32s2
platform = ${esp32_lolin_s2_mini.platform}
lib_deps = ${esp32_lolin_s2_mini.lib_deps}
test_ignore = ${esp32_lolin_s2_mini.test_ignore}
